# Generated by Django 2.0.13 on 2019-08-23 21:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190824_0003'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='created_on',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2019, 8, 23, 21, 25, 38, 594931, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
