# Generated by Django 2.0.13 on 2019-08-26 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_remove_post_images'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.AddField(
            model_name='category',
            name='last_modified',
            field=models.DateField(auto_now=True),
        ),
    ]
