# Generated by Django 2.0.5 on 2019-09-17 21:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_carousel'),
    ]

    operations = [
        migrations.AddField(
            model_name='carousel',
            name='created_on',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2019, 9, 17, 21, 30, 43, 5522, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carousel',
            name='last_modified',
            field=models.DateField(auto_now=True),
        ),
    ]
